base_images:
  assisted-service-scripts:
    name: ocm-2.12
    namespace: edge-infrastructure
    tag: assisted-service-scripts
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: hypershift-operator
    namespace: hypershift
    tag: latest
  hypershift-tests:
    name: hypershift-tests
    namespace: hypershift
    tag: latest
  test-bin:
    name: "4.17"
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: "4.17"
    namespace: ocp
    tag: upi-installer
releases:
  414-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.14"
  415-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.15"
  416-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.16"
  417-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.17"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.17"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.17"
  stable-latest:
    release:
      architecture: amd64
      channel: candidate
      version: "4.17"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-powervs-agent-connected-hub415-mce27-hc417-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      HOSTEDCLUSTER_RELEASE_IMAGE_LATEST: release:417-latest
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:415-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.7"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powervs-agent-connected-hub416-mce27-hc417-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      HOSTEDCLUSTER_RELEASE_IMAGE_LATEST: release:417-latest
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:416-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.7"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
zz_generated_metadata:
  branch: release-4.17
  org: openshift
  repo: hypershift
  variant: periodics-mce
