base_images:
  assisted-service-scripts:
    name: ocm-2.10
    namespace: edge-infrastructure
    tag: assisted-service-scripts
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: "4.15"
    namespace: ocp
    tag: hypershift-operator
  hypershift-tests:
    name: "4.15"
    namespace: ocp
    tag: hypershift-tests
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.15"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.15"
  upi-installer:
    name: "4.15"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.15"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: hypershift-mce-power-e2e-f7
  cron: 0 16 * * *
  steps:
    cluster_profile: aws
    env:
      ARCHITECTURE: ppc64le
      BASE_DOMAIN: ocp-dev-ppc64le.com
      MCE_VERSION: "2.5"
      TEST_FILTERS: ~NonHyperShiftHOST
    test:
    - chain: openshift-e2e-test-qe
    workflow: hypershift-mce-power-conformance
zz_generated_metadata:
  branch: openshift-release-4.15
  org: openshift
  repo: hypershift
  variant: periodics
