base_images:
  assisted-service-scripts:
    name: ocm-2.9
    namespace: edge-infrastructure
    tag: assisted-service-scripts
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: hypershift-operator
    namespace: hypershift
    tag: latest
  hypershift-tests:
    name: hypershift-tests
    namespace: hypershift
    tag: latest
  test-bin:
    name: "4.14"
    namespace: ocp
    tag: hypershift-tests
  upi-installer:
    name: "4.14"
    namespace: ocp
    tag: upi-installer
releases:
  414-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.14"
  415-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.15"
  416-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.16"
  417-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.17"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-powevs-agent-connected-hub417-mce27-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:417-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.7"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powevs-agent-connected-hub416-mce27-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:416-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.7"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powevs-agent-connected-hub416-mce26-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:416-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.6"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powevs-agent-connected-hub415-mce27-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:415-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.7"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powevs-agent-connected-hub415-mce26-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:415-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.6"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powevs-agent-connected-hub415-mce25-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:415-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.5"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powevs-agent-connected-hub414-mce26-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:414-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.6"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
- as: e2e-powevs-agent-connected-hub414-mce24-hc414-conformance
  cron: 0 6 * * *
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:414-latest
    env:
      ADDITIONAL_HYPERSHIFT_NODEPOOL_CONFIG: |
        NAME_SUFFIX=power, CPU_ARCH=ppc64le, NODE_ARCH=ppc64le
      MCE_VERSION: "2.4"
      TEST_SUITE: openshift/conformance/parallel/minimal
    workflow: hypershift-mce-power-conformance
zz_generated_metadata:
  branch: release-4.14
  org: openshift
  repo: hypershift
  variant: periodics-mce
